[phases.setup]
nixPkgs = ["php82", "php82Extensions.pdo", "php82Extensions.pdo_mysql", "php82Extensions.mbstring", "php82Extensions.xml", "php82Extensions.zip", "php82Extensions.gd", "php82Extensions.intl", "php82Extensions.curl", "php82Extensions.fileinfo", "composer"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader --ignore-platform-reqs"]

[phases.build]
cmds = [
    "php artisan route:cache",
    "php artisan view:cache",
    "php artisan storage:link"
]

[start]
cmd = "php artisan migrate --force && php artisan db:seed --force && php artisan serve --host 0.0.0.0 --port $PORT"
